### ISSUE TITLE
Linux version when?

### ISSUE THREAD

**Issue by SwirlyStone5877** [potatoTeto/fur2uge#1]
Both Furnace and GB Studio are on other operating systems than Windows (Linux, MacOS...), so naturally  this must be as well, right? Nope. Windows only. No make or cmake compatibility either, it's only for Windows. I suggest we change this, as making it cross-platform would make a lot of users happy. Take, for example, me. I use Linux daily, and I also develop GB games from time to time, mainly tiny little demos. Sometimes, I need music. I open up Furnace and absolutely cook, but then realize that I can't convert this once I'm finished. Please, make this cross-platform in Python or C or literally anything else.

**Comment by IFEware** [comment]
I second this.
Running .NET applications under wine is as possible as completing the minus world and the lack of linux compatibility leaves me deeply frustrated

**Comment by StudioGuma** [comment]
Thirding, as someone who's come to prefer Furnace over hUGETracker. I tried to compile fur2uge from source using .NET on Linux, but I got 65 warnings and a confusing `Object reference not set to an instance of an object.` syntax error when trying to run, even though I didn't change the code at all.

**Comment by potatoTeto** [comment]
Hi there! Apologies for the delayed response—I’ve been busy composing.

The source code should be compatible with Mac and Linux as is. I’ve also compiled some binaries for the new version, which I just released: https://github.com/potatoTeto/fur2uge/releases

Fingers crossed that it works well for you all! Please let me know if there are any additional issues with these binaries 🙏

**Comment by SwirlyStone5877** [comment]
Oh, nice! Thank you!
